
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-postgresql
  namespace: bamboo
  labels:
    app: bamboo-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bamboo-postgresql
  template:
    metadata:
      labels:
        app: bamboo-postgresql
    spec:
      hostname: bamboo-postgresql
      subdomain: bamboo-postgresql-svc
      initContainers:
      - name: chmod-er
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: postgresql-data
          mountPath: /data
      containers:
        - name: bamboo-postgresql
          image: postgres:10.19
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: postgres-config    
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: pvc-bamboo-postgresql