apiVersion: v1
kind: Service
metadata:
  name: bamboo-postgresql-svc
  namespace: bamboo
spec:
  selector:
    app: bamboo-postgresql
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  loadBalancerIP: 10.10.150.9    