apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: confluence
spec:
  selector:
    app: postgresql
  type: LoadBalancer
  # type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  loadBalancerIP: 10.10.150.7  