apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bamboo
  name: bamboo-config-db
  labels:
    app: bamboo-server
data:
  bamboo.cfg.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <application-configuration>
      <setupStep>complete</setupStep>
      <setupType>custom</setupType>
      <buildNumber>70015</buildNumber>
      <properties>
        <property name="attachments.dir">${bambooHome}/attachments</property>
        <property name="bamboo.artifacts.directory">${bambooHome}/artifacts</property>
        <property name="bamboo.config.directory">${bambooHome}/xml-data/configuration</property>
        <property name="bamboo.jms.broker.client.uri">failover:(tcp://k8s-bamboo.okbtsp.com:54663?wireFormat.maxInactivityDuration=300000)?maxReconnectAttempts=10&amp;initialReconnectDelay=15000</property>
        <property name="bamboo.jms.broker.uri">nio://0.0.0.0:54663?wireFormat.maxInactivityDuration=300000</property>
        <property name="bamboo.project.directory">${bambooHome}/xml-data/builds</property>
        <property name="bamboo.repository.logs.directory">${bambooHome}/xml-data/repository-specs</property>
        <property name="buildWorkingDir">${bambooHome}/xml-data/build-dir</property>
        <property name="hibernate.c3p0.acquire_increment">3</property>
        <property name="hibernate.c3p0.idle_test_period">30</property>
        <property name="hibernate.c3p0.max_size">100</property>
        <property name="hibernate.c3p0.max_statements">0</property>
        <property name="hibernate.c3p0.min_size">3</property>
        <property name="hibernate.c3p0.timeout">120</property>
        <property name="hibernate.connection.driver_class">org.postgresql.Driver</property>
        <property name="hibernate.connection.password">NBRNgzznATn4f4wnskKFx8x</property>
        <property name="hibernate.connection.url">jdbc:postgresql://bamboo-postgresql-svc.bamboo.svc.cluster.local:5432/bamboo</property>
        <property name="hibernate.connection.username">limiteduser</property>
        <property name="hibernate.dialect">org.hibernate.dialect.PostgreSQL82Dialect</property>
        <property name="hibernate.setup">true</property>
        <property name="license.string">AAABUA0ODAoPeNptUUtvwjAMvudXRNplOxSF8hAgRRq0ObDxqGi1u1sMi0gTlKRo/PuVlkogcbT92 d/Dbyl4+lVpyiaUDWaj8Ww4pVGc0ZD1pySHMjemt5IFaodiL700motNJnbJbpkKEhntofAbKJGDk nByKGleFb/g3Ul2+5uqzNFuD4umXJkC1PyI2jse9ElS2RruMAaP/MYasGHQn5CO9O8s7bUZVlrJU nrcd7RiDVJx2Jef5pR7d+4Vpuw467G8IPe2wtcydlgaj3cdo9eYRIFuRD4HkV3P2FiOtuu12EXL+ YrUUrRHDbp4lByykN393E+kHqxHyw+gHHYmlzFfLeNUbIL+YMLGQzYldcGfGlt7BC0dNC/Yfi9ol iYkstg0HsIbB2xCVHv3B627wUMSoyusPDfLrTf6nqK9oP2gI9pmQdswiLiAqlqeVuU/4365fDAsA hQmZDTreDd7uXkhP7oGm+TeLlkefQIUFMrL5O4AKn2lFqkDYcmP2wfGjN4=X02gk</property>
        <property name="lucene.index.dir">${bambooHome}/index</property>
        <property name="serverId">BB72-NLCT-SJ89-DRCM</property>
        <property name="serverKey">975</property>
        <property name="webwork.multipart.saveDir">${bambooHome}/temp</property>
      </properties>
    </application-configuration>