apiVersion: v1
kind: Service
metadata:
  name: bamboo-external-svc
  namespace: bamboo
  labels:
    app: bamboo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: ssh
      port: 54663
      targetPort: 54663
      protocol: TCP  
  # sessionAffinity: ClientIP
  # loadBalancerIP: 10.10.150.12
  selector:
    app: bamboo