apiVersion: v1
kind: ConfigMap
metadata:
  namespace: traefik
  name: dynamic-toml
data:
  dynamic.toml: |
    [[tls.certificates]]
        certFile = "/certs/cert.crt"
        keyFile = "/certs/cert.key"
        stores = ["default"]
         
    