
replicaCount: 1
image:
  repository: registry.okbtsp.com/devops/confluence-server
  pullPolicy: IfNotPresent
  tag: "7.3.5"
database:
  type: postgresql 
  url: jdbc:postgresql://postgresql.postgresql-svc.confluence.svc.cluster.local:5432/confluence
  credentials:
    secretName: confluence-postgres
    usernameSecretKey: username
    passwordSecretKey: password
volumes:
  localHome:
    # persistentVolumeClaim:
    #   create: true
    #   storageClassName: nfs-csi
    #   resources:
    #     requests:
    #       storage: 80Gi
    persistentVolumeClaim:
      create: false
    customVolume:
      persistentVolumeClaim:
         claimName: "pvc-confluence"
    # mountPath: "/var/atlassian/application-data/confluence"
  sharedHome:
    persistentVolumeClaim:
      create: true
      storageClassName: nfs-csi
      resources:
        requests:
          storage: 2Gi
    mountPath: "/var/atlassian/application-data/shared-home"      

  synchronyHome:
    persistentVolumeClaim:
      create: true
      storageClassName: nfs-csi
      resources:
        requests:
          storage: 2Gi
    # persistentVolumeClaim:
    #   create: false
    # customVolume:
    #   persistentVolumeClaim:
    #      claimName: "pvc-confluence-sync"
    mountPath: "/var/atlassian/application-data/confluence"

  # additional:
  #   - name: confluencenfs
  #     persistentVolumeClaim:
  #        claimName: "pvc-confluence "

additionalFiles:
 - name: confluence-config-web
   type: configMap
   key: server.xml
   mountPath: /opt/atlassian/confluence/conf/      
# Confluence configuration
#
confluence:
  service:
    port: 80
    type: ClusterIP
    contextPath:
  securityContext:
    fsGroup: 2002
  ports:
    http: 8090
    hazelcast: 5701
  # Confluence licensing details
  license:
    secretName: confluence-license
    secretKey: license
  # Data Center clustering
  clustering:
    enabled: false
    usePodNameAsClusterNodeName: true
  # Confluence Pod resource requests
  resources:

    jvm:
      maxHeap: "8g"
      minHeap: "1g"
      reservedCodeCache: "512m"
    container: 
      requests:
        cpu: "2"
        memory: "8G"
      limits:
        cpu: "2"
        memory: "8G"

  additionalJvmArgs:
    - -XX:ActiveProcessorCount=2
    - -Datlassian.plugins.enable.wait=300 -DXX:MaxRAM=8g
  additionalEnvironmentVariables:
    - name: ATL_PROXY_NAME
      value: "wiki.okbtsp.com"
    - name: ATL_TOMCAT_SCHEME
      value: "https"
    - name: ATL_TOMCAT_SECURE
      value: "true"
    - name: ATL_PROXY_PORT
      value: "443"  
# Confluence Synchrony configuration
synchrony:
  enabled: true
  service:
    port: 80
    type: ClusterIP
  setPermissions: true
  ports:
    http: 8091
    hazelcast: 5701  

# additionalVolumeMounts:
#   - volumeName: confluencenfs
#     mountPath: /var/atlassian/nfs
        
