apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-confluence
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: confluence
    name: pvc-confluence
  nfs:
    path: /Confluence
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-confluence
  namespace: confluence
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi    
  volumeName: pv-confluence

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-confluence-sync
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: confluence
    name: pvc-confluence-sync
  nfs:
    path: /Confluence-Sync
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-confluence-sync
  namespace: confluence
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi    
  volumeName: pv-confluence-sync  