apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: awx
    name: pvc-awx
  nfs:
    path: /AWX
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-awx
  namespace: awx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi    
  volumeName: pv-awx