apiVersion: v1
kind: Service
metadata:
  name: artifactory-external
  namespace: jfrog
  labels:
    app: artifactory
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082  
      targetPort: 8082
      protocol: TCP
  # sessionAffinity: ClientIP
  selector:
    app: artifactory