apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jfrog
spec:
  capacity:
    storage: 1400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jfrog
    name: pvc-jfrog
  nfs:
    path: /Artifactory
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jfrog
  namespace: jfrog
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1400Gi    
  volumeName: pv-jfrog