
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-postgresql
  namespace: jira
  labels:
    app: jira-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-postgresql
  template:
    metadata:
      labels:
        app: jira-postgresql
    spec:
      hostname: jira-postgresql
      subdomain: jira-postgresql-svc
      initContainers:
      - name: chmod-er
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: postgresql-data
          mountPath: /data
      containers:
        - name: jira-postgresql
          image: postgres:11.14
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: postgres-config    
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: pvc-jira-postgresql 
# ---
# # PostgreSQL StatefulSet
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: jira-postgresql
#   namespace: jira
# spec:
#   serviceName: jira-postgresql-service
#   selector:
#     matchLabels:
#       app: jira-postgresql
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: jira-postgresql
#     spec:
#       containers:
#         - name: jira-postgresql
#           image: postgres:latest
#           ports:
#             - containerPort: 5432
#           volumeMounts:
#             - name: postgresql-data
#               mountPath: /data
#           envFrom:
#             - configMapRef:
#                 name: postgres-config    
#       volumes:
#         - name: postgresql-data
#           persistentVolumeClaim:
#             claimName: pvc-jira-postgresql       
        