apiVersion: v1
kind: Service
metadata:
  name: jira-postgresql-svc
  namespace: jira
spec:
  selector:
    app: jira-postgresql
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  loadBalancerIP: 10.10.150.6