apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jira-postgresql
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jira
    name: pvc-jira-postgresql
  nfs:
    path: /Jira-Postgres
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jira-postgresql
  namespace: jira
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-jira-postgresql        

  