          
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfrog-postgresql
  namespace: jfrog
  labels:
    app: jfrog-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jfrog-postgresql
  template:
    metadata:
      labels:
        app: jfrog-postgresql
    spec:
      hostname: jfrog-postgresql
      subdomain: jfrog-postgresql-svc
      initContainers:
      - name: chmod-er
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: postgresql-data
          mountPath: /data
      containers:
        - name: jfrog-postgresql
          image: postgres:13.5
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: postgres-config    
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: pvc-jfrog-postgresql 
        