apiVersion: v1
kind: Service
metadata:
  name: jfrog-postgresql-svc
  namespace: jfrog
spec:
  selector:
    app: jfrog-postgresql
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  loadBalancerIP: 10.10.150.10