apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jfrog-postgresql
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jfrog
    name: pvc-jfrog-postgresql
  nfs:
    path: /Artifactory-Postgres
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jfrog-postgresql
  namespace: jfrog
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi    
  volumeName: pv-jfrog-postgresql  