apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/chart: awx-operator-0.25.0
  labels:
    control-plane: controller-manager
  name: awx-operator-controller-manager-metrics-service
  namespace: awx
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager

