apiVersion: v1
kind: Service
metadata:
  name: awx-postgresql-svc
  namespace: awx
spec:
  selector:
    app: awx-postgres
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  loadBalancerIP: 10.10.150.11   