apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx-postgresql
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: awx
    name: pvc-awx-postgresql
  nfs:
    path: /AWX-Postgres
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-awx-postgresql
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi    
  volumeName: pv-awx-postgresql    