apiVersion: v1
kind: Service
metadata:
  name: bitbucket-postgresql-svc
  namespace: bitbucket
spec:
  selector:
    app: bitbucket-postgresql
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  loadBalancerIP: 10.10.150.8