apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bitbucket-postgresql
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: bitbucket
    name: pvc-bitbucket-postgresql
  nfs:
    path: /Bitbucket-Postgres
    server: 10.10.150.126

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bitbucket-postgresql
  namespace: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi    
  volumeName: pv-bitbucket-postgresql